### ISSUE TITLE
Tremulous launcher hangs if you don't have tremulous installed?

### ISSUE THREAD

**Issue by wtfbbqhax** [GrangerHub/tremulous-launcher#4]
PLATFORM: OSX

Perhaps this is not strictly the issue as I am perceiving it, but running the launcher tells me "An update is available!"

So I click the Yep/Ok Option

Next, it is "running Tremulous", and just hangs.

---

I run tremulous from an local directory, and do not have an "/Applications/Tremulous.app", so perhaps it is hanging for this reason, or perhaps it is supposed to download tremulous first.

**Comment by jkent** [comment]
Platform specific code for OSX hasn't been written yet... this is a TODO
